cam_name = 'cam_1'

[camera_info]
vendor_name = "John Doe                   "
model_name = "Fake Camera                  "
firmware_version = 1
focal_length = 8.0
sensor_size_h = 6.0
sensor_size_v = 4.0
resolution_h = 1920
resolution_v = 1080
lens_id = 0
flags = 0
cam_definition_version = 1
cam_definition_uri = "http://example.com/camera_definition.xml"

[camera_position]
x = 0.0
y = 0.0
z = 0.0
roll = 0.0
pitch = 0.0
yaw = 0.0

[gstreamer_video_src]
fps = 1
loglevel = 'DEBUG'   # todo add loglevel to all pipelines and to gst_utils

pipeline = [
     "nvarguscamerasrc sensor_id=1 ! video/x-raw(memory:NVMM),width=4032, height=3040, framerate=30/1, format=NV12 ",
    # 'videorate max-rate={fps} drop-only=true ! queue max-size-buffers=3 leaky=downstream',
    'tee name=t',

    # "t.",
    # 'queue leaky=2 ! intervideosink channel={cam_name}  sync=false',

    "t.",
    'interpipesink name={cam_name} ',
]



# streaming pipelines

[gstreamer_udpsink]
fps = 2
host = '*camera_UDP_IP*'     # overwrite with server_config.toml
port = '*cam_1_UDP_port*'    # overwrite with server_config.toml
bitrate=2000000

pipeline = [
    'interpipesrc listen-to={cam_name} is-live=false allow-renegotiation=true format=time',
    'valve name=myvalve drop=False ',
    'videorate max-rate={fps} drop-only=true skip-to-first=true ! video/x-raw(memory:NVMM),framerate={fps}/1',
    'nvvidconv ! video/x-raw(memory:NVMM), width=2000, height=1500, format=NV12',
    # 'queue',
    'nvv4l2h265enc bitrate={bitrate} iframeinterval=10 insert-sps-pps=true  preset-level=UltraFastPreset EnableTwopassCBR=false maxperf-enable=true',
    'rtph265pay config-interval=1 ! udpsink host={host} port={port} sync=false async=false',
    ]

[gstreamer_jpg_filesink]
fps = 10   # Frames per second * 10
quality = 95
filenames = '%03d.jpg'
index = 0

pipeline = [
    'interpipesrc listen-to={cam_name} is-live=false allow-renegotiation=true format=time',
    'queue',
    'videorate drop-only=true skip-to-first=true ! video/x-raw(memory:NVMM), framerate={fps}/20',
    'nvvidconv ! video/x-raw(memory:NVMM), format=I420',
    'nvjpegenc quality={quality} idct-method=1',
    'multifilesink location={save_path}/{cam_name}/{filenames} index={index}',
    ]


