[camera_info]
vendor_name = "John Doe                   "
model_name = "Fake Camera                  "
firmware_version = 1
focal_length = 8.0
sensor_size_h = 6.0
sensor_size_v = 4.0
resolution_h = 1920
resolution_v = 1080
lens_id = 0
flags = 0
cam_definition_version = 1
cam_definition_uri = "http://example.com/camera_definition.xml"

[camera_position]
x = 0.0
y = 0.0
z = 0.0
roll = 0.0
pitch = 0.0
yaw = 0.0

[gstreamer_video_src]
fps = 30   # Frames per second
width = 800
height = 600
loglevel = 'DEBUG'   # todo add loglevel to all pipelines and to gst_utils

pipeline = [
    'videotestsrc pattern=ball is-live=true ! timeoverlay',
    'textoverlay text="Front" valignment=top halignment=right font-desc="Sans, 18" shaded-background=true',
    'capsfilter caps=video/x-raw,format=RGB,width={width},height={height},framerate={fps}/1',
    'tee name=t',

    "t.",
    'queue', 'videoscale ', 'capsfilter caps=video/x-raw,format=RGB,width=400,height=300',
    'videoconvert ! autovideosink',

    "t.",
    'queue leaky=2 ! intervideosink channel=channel_0  sync=false',

    "t.",
    'queue leaky=2 ! intervideosink channel=channel_1  sync=false',

    "t.",
    'interpipesink name=cam_0 ',
]


[gstreamer_jpg_filesink]
fps = 10   # Frames per second
width = 800
height = 600
quality = 85
pipeline = [
    'intervideosrc channel=channel_1 ',
    'videoconvert ! videoscale ! video/x-raw,width={width},height={height},framerate={fps}/1',
    'queue',
    'jpegenc quality={quality}',  # Quality of encoding, default is 85
    'appsink name=mysink emit-signals=True max-buffers=1 drop=True',
    ]

# todo add video save pipeline

# streaming pipelines

[gstreamer_udpsink]
port = 5000
bitrate=2000
pipeline = [

    'interpipesrc listen-to=cam_0 is-live=true allow-renegotiation=true format=time',
    'valve name=myvalve drop=False ',
    'queue',
#    'capsfilter caps=video/x-raw,width={width},height={height},framerate={fps}/1',
    'videoconvert',
    'x265enc bitrate={bitrate}',
    'rtph265pay config-interval=1 ! udpsink host=127.0.0.1 port={port} sync=true',
    ]





