cam_name = 'cam_1'
[camera_info]
vendor_name = "John Doe                   "
model_name = "Fake Camera                  "
firmware_version = 1
focal_length = 8.0
sensor_size_h = 6.0
sensor_size_v = 4.0
resolution_h = 1920
resolution_v = 1080
lens_id = 0
flags = 0
cam_definition_version = 1
cam_definition_uri = "http://example.com/camera_definition.xml"

[camera_position]
x = 0.0
y = 0.0
z = 0.0
roll = 0.0
pitch = 0.0
yaw = 0.0

[gstreamer_video_src]
fps = 30   # Frames per second
width = 800
height = 600
loglevel = 'DEBUG'   # todo add loglevel to all pipelines and to gst_utils

pipeline = [
    'videotestsrc pattern=ball is-live=true ! timeoverlay',
    'textoverlay text="Left" valignment=top halignment=right font-desc="Sans, 18" shaded-background=true',
    'capsfilter caps=video/x-raw,format=RGB,width={width},height={height},framerate={fps}/1',
    'tee name=t',

    "t.",
    'queue', 'videoscale ', 'capsfilter caps=video/x-raw,format=RGB,width=400,height=300',
    'videoconvert ! autovideosink',

#    "t.",
#    'queue leaky=2 ! intervideosink channel=channel_0  sync=false',
#
#    "t.",
#    'queue leaky=2 ! intervideosink channel={cam_name}  sync=false',

    "t.",
    'interpipesink name={cam_name} ',
]

[gstreamer_udpsink]
fps=2
host = '*camera_UDP_IP*'     # overwrite with server_config.toml
port = '*cam_1_UDP_port*'    # overwrite with server_config.toml
pipeline = [

    'interpipesrc listen-to={cam_name} is-live=true allow-renegotiation=true format=time',
    'valve name=myvalve drop=False ',
    'queue',
    'videorate drop-only=true skip-to-first=true ! video/x-raw,framerate={fps}/1',
    'videoconvert',
     'x264enc tune=zerolatency noise-reduction=10000 bitrate=2048 speed-preset=superfast',
#    'x264enc tune=zerolatency',
    'rtph264pay ! udpsink host={host} port={port} sync=true',
    ]


[gstreamer_jpg_filesink]
fps = 10   # Frames per second * 10
quality = 85
filenames = '%03d.jpg'
index = 0

pipeline = [
    'interpipesrc listen-to={cam_name} is-live=false allow-renegotiation=true format=time',
    'queue',
    'videorate drop-only=true skip-to-first=true ! video/x-raw,framerate={fps}/10',
    'videoconvert ! video/x-raw, format=I420',
    'jpegenc quality={quality}',  # Quality of encoding, default is 85
    'multifilesink location={save_path}/{cam_name}/{filenames} max-files=10 index={index}',
    ]



